ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS payment_option VARCHAR(32),
  ADD COLUMN IF NOT EXISTS invoice_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS requisite_card VARCHAR(64),
  ADD COLUMN IF NOT EXISTS requisite_bank VARCHAR(128),
  ADD COLUMN IF NOT EXISTS requisite_owner VARCHAR(128),
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;